Dinamične spletne rešitve/DRS_Simunovic/DRS_Simunovic/Controllers/RegistrationController.cs
using DRS_Simunovic.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DRS_Simunovic.Controllers
{
    public class RegistrationController : Controller
    {

        [HttpGet]
        public IActionResult Index()
        {
            Uporabnik uporabnik = new Uporabnik();
            return View(uporabnik);
        }

        //private readonly UserManager<IdentityUser> _userManager;
        //private readonly UserManager<IdentityUser> _userManager = new UserManager<IdentityUser>(new UserStore<IdentityUser>());



        [HttpPost]
        public async Task<IActionResult> Index(Uporabnik uporabnik)
        {
            if (ModelState.IsValid)
            {

                IdentityUser user = new IdentityUser { UserName = uporabnik.Eposta, Email = uporabnik.Eposta };
                //RoleManager<IdentityRole> roleManager = new RoleManager<IdentityRole, "Admin">();
                UserManager<IdentityUser> _userManager = new UserManager<IdentityUser>(new UserStore<IdentityUser>(AtletikaContext.Instance));
                var result = await _userManager.CreateAsync(user, uporabnik.Geslo);
                if (result.Succeeded)
                {
                    await _userManager.AddToRoleAsync(user.Id, "User");
                    TempData["Uporabnik"] = "xxx";

                    AtletikaContext context = AtletikaContext.Instance;
                    context.uporabniks.Add(uporabnik);
                    await context.SaveChangesAsync();

                    return RedirectToAction("PrikazPodatkov", uporabnik);
                }

            }
            return View();
        }

        [HttpGet]
        public IActionResult VpisNaslova()
        {
            if (TempData["Uporabnik"] == null)
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpPost]
        public IActionResult VpisNaslova(NaslovUporabnika nu)
        {
            TempData["Naslov"] = nu.Naslov;
            TempData["DataNaslov"] = nu.Naslov;
            TempData["DataPostnaStevilka"] = nu.PostnaStevilka;
            TempData["DataDrzava"] = nu.Drzava;
            return RedirectToAction("VpisVpisnihPodatkov");
        }


        [HttpGet]
        public IActionResult VpisVpisnihPodatkov()
        {
            if (TempData["Naslov"] == null)
            {
                return RedirectToAction("Index");
            }
            return View();
        }


        [HttpPost]
        public IActionResult VpisVpisnihPodatkov(VpisniPodatki vp)
        {
            TempData["VpisniPodatki"] = "vp";
            TempData["DataEposta"] = vp.Eposta;
            TempData["DataGeslo"] = vp.Geslo;
            if (vp.Geslo == vp.Geslo1)
            {

                return RedirectToAction("PrikazPodatkov");
            }

            return RedirectToAction("Index");
        }


        public IActionResult PrikazPodatkov(Uporabnik uporabnik)
        {
            if (TempData["Uporabnik"] == null)
            {
                return RedirectToAction("Index");
            }


            return View(uporabnik);
        }

    }
}

Dinamične spletne rešitve/DRS_Simunovic/DRS_Simunovic/Controllers/SportnikController.cs
using DRS_Simunovic.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DRS_Simunovic.Controllers
{
    public class SportnikController : Controller
    {

        public IActionResult Index()
        {
            AtletikaContext context = AtletikaContext.Instance;
            VsiSportniki vsiSportniki = new VsiSportniki();
            vsiSportniki.sportniks = context.Sportniks.Where(x => x.ID != -1).ToList();
            return View(vsiSportniki);
        }

       
        [HttpPost]
        public IActionResult Dodajanje(Sportnik sportnik)
        {
            if (sportnik.DoubleDaPokažemDaDela > 100)
            {
                sportnik.DoubleDaPokažemDaDela = sportnik.DoubleDaPokažemDaDela / 10.0;
            }

            AtletikaContext context = AtletikaContext.Instance;
            context.Sportniks.Add(sportnik);
            context.SaveChanges();

            return RedirectToAction("PrikazPodatkov", sportnik);
        }

        public IActionResult PrikazPodatkov(Sportnik sportnik)
        {
            return View(sportnik);
        }


        [HttpGet]
        public IActionResult Dodajanje()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Uredi(Sportnik sportnik)
        {
            if (sportnik != null)
            {
                return View(sportnik);
            }
            else
                return RedirectToAction("Index");
        }

        [HttpPost]
         public IActionResult UrediSportnika(Sportnik sportnik)
        {
            if (sportnik != null)
            {
                AtletikaContext context = AtletikaContext.Instance;
                var sp = context.Sportniks.Where(x => x.ID == sportnik.ID).Single();
                sp.Name = sportnik.Name;
                sp.LastName = sportnik.LastName;
                context.SaveChanges();
                return RedirectToAction("PrikazPodatkov", sportnik);
            }
            else
                return RedirectToAction("Index");
        }

        public IActionResult Izbrisi(Sportnik sportnik)
        {
            AtletikaContext context = AtletikaContext.Instance;
            context.Sportniks.Remove(context.Sportniks.Where(x => x.ID == sportnik.ID).SingleOrDefault());
            context.SaveChanges();
            return RedirectToAction("Index");
        }



    }
}

Dinamične spletne rešitve/DRS_Simunovic/DRS_Simunovic/Controllers/TekmovanjeController.cs
using DRS_Simunovic.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DRS_Simunovic.Controllers
{
    public class TekmovanjeController : Controller
    {
        public IActionResult Index()
        {
            List<Tekmovanje> tekmovanjes = AtletikaContext.Instance.tekmovanjes.Where(x => x.ID != -1).ToList();
            VsaTekmovanja vsaTekmovanja = new VsaTekmovanja();
            vsaTekmovanja.Tekmovanjes = tekmovanjes;
            return View(vsaTekmovanja);
        }
        
        
        public IActionResult Dodajanje()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Dodajanje(Tekmovanje tekmovanje)
        {
            AtletikaContext context = AtletikaContext.Instance;
            context.tekmovanjes.Add(tekmovanje);
            context.SaveChanges();
            return RedirectToAction("PrikazPodatkov", tekmovanje);
        }

        public IActionResult PrikazPodatkov(Tekmovanje tekmovanje)
        {
            return View(tekmovanje);
        }

        [HttpGet]
        public IActionResult Uredi(Tekmovanje tekmovanje)
        {
            if (tekmovanje != null)
            {
                return View(tekmovanje);
            }
            else
                return RedirectToAction("Index");
        }

        public IActionResult UrediTekmovanje(Tekmovanje tekmovanje)
        {
            AtletikaContext context = AtletikaContext.Instance;
            var tekma = context.tekmovanjes.Where(x => x.ID == tekmovanje.ID).Single();
            tekma.Name = tekmovanje.Name;
            tekma.venue = tekmovanje.venue;

            context.SaveChanges();
            return RedirectToAction("PrikazPodatkov", tekmovanje);
        }

        //[HttpDelete]
        public IActionResult Izbrisi(Tekmovanje tekmovanje)
        {
            AtletikaContext context = AtletikaContext.Instance;
            context.tekmovanjes.Remove(context.tekmovanjes.Where(x => x.ID == tekmovanje.ID).SingleOrDefault());
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Dinamične spletne rešitve/DRS_Simunovic/DRS_Simunovic/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DSR_Simunovic</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    @*<link rel="stylesheet" href="/resources/demos/style.css">*@
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <script>
        $(function () {
            $("#accordion").accordion();
        });
    </script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Sportnik" asp-action="Index">DRS_Simunovic</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sportnik" asp-action="Index">Sportnik</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tekmovanje" asp-action="Index">Tekomvanje</a>
                        </li>
                    </ul>
                    <strong>@DateTime.Now.ToString("dd. MM. yyyy, HH:mm")</strong>
                    <a class="nav-link text-dark" asp-controller="Registration" asp-action="Index">Registracija</a>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container  d-flex justify-content-center">
            Naredu sm js
        </div>
    </footer>
    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>*@
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>